### PR TITLE
Fix PrivateKey.toBuffer

### PR DESCRIPTION
**Pull request by fanatid**
Issue: #47

### CODE REVIEW

**Comment by braydonf** [comment]
Thanks for taking a look at this! 

This has come up before (https://github.com/bitpay/bitcore/issues/1270), and the solution was to use:
```js
privateKey.bn.toString(16, 32); // base 16, zero padded to 32 bytes
```

The solution in this PR is also useful:
```js
privateKey.bn.toBuffer({ size: 32 });
```
There may be [implementations](https://github.com/bitpay/bitcore-wallet-client/blob/1dba5651ed26e2f20e3fb33d9f66faec0152ce35/lib/common/utils.js#L74) that don't make a distinction and would break as a result? So it could be good to keep this as optional for the time being, and put into a next major release watch list.

**Comment by fanatid** [comment]
Agree, it should be major release, but major should be released ASAP.
Many of this bugs can be avoided if `bitcore-lib` will use [cryptocoinjs/secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node) (related #41)

**Comment by afk11** [comment]
@fanatid secp256k1-node doesn't work in a browser, so unfortunately an alternative is still required. 

@braydonf Padding shouldn't be optional behavior, you should get used to doing it anywhere you serialize to binary/hex, lest something like the following happens:

 1. Public key is compressed, and top 8 bits of Px are zero. 
 2. Key is serialized to a length of 32 bytes instead of 33. 
 3. Hash this, produce an address.
 4. Funds are unrecoverable

**Comment by braydonf** [comment]
@afk11 FYI, it's not an issue with `publicKey.toBuffer()`

**Comment by jprichardson** [comment]
> @fanatid secp256k1-node doesn't work in a browser, so unfortunately an alternative is still required.

@afk11 this is incorrect. From the readme:

> Works on node version 0.10 or greater and in the Browser via browserify.

**Comment by afk11** [comment]
@jprichardson woops, I assumed it was just the C bindings.

**Comment by braydonf** [comment]
@fanatid I've created a 1.0.0 branch for collaboration on changes that need an API change. As discussed. This issue affects hd key derivation, and will likely need this to be the default, but optionally disabled.

**Comment by braydonf** [comment]
I've brought this into the 1.0.0 branch at: https://github.com/bitpay/bitcore-lib/tree/1.0.0

**Comment by braydonf** [comment]
How this relates to hd derivation is handled in: https://github.com/bitpay/bitcore-lib/pull/97

**Pull request closed without merging**
