### PR TITLE
Fixing index.js - require buffer

### PR DESCRIPTION
**Pull request by AnthonyAkentiev**
This change is required in order to run in my project.

### CODE REVIEW

**Comment by fanatid** [comment]
OOI, where you using bitcore-lib?
Are you using webpack or browserify?

**Comment by AnthonyAkentiev** [comment]
@fanatid I'm using it through 'eth-lightwallet' library.

**Comment by fanatid** [comment]
@AnthonyAkentiev I think that if you want to fix library, you should change not only `index.js`

Right now `bitcore-lib` has mess with `Buffer`:
```bash
$ git log --pretty=oneline -1
f6b0b14ac655c5eec499591b4e4d26b0b2491016 Bump package version to 0.13.19
$ grep "require('buffer')" -rnl lib |wc -l
9
$ grep "new Buffer" -rnl lib |wc -l
28
```

Check [hdprivatekey.js](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/hdprivatekey.js) for example:
* [creating buffer from buffer module](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/hdprivatekey.js#L183)
* [creating buffer from global Buffer](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/hdprivatekey.js#L414)

Or [encoding/base58.js](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/encoding/base58.js):
* [Buffer.isBuffer](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/encoding/base58.js#L14)
* [buffer.Buffer.isBuffer](https://github.com/bitpay/bitcore-lib/blob/f6b0b14ac655c5eec499591b4e4d26b0b2491016/lib/encoding/base58.js#L26)

<hr>

But what `bitcore-lib` really should use? Global `Buffer` or module `buffer`?

**Comment by AnthonyAkentiev** [comment]
I think that It's better to open an issue and to fix that mess. My PullRequest will only fix error in my project.

**Comment by braydonf** [comment]
How do you reproduce the issue?

**Comment by matiu** [comment]
Closing, too old / stalled. Please reopen if active.

**Pull request closed without merging**
