### PR TITLE
remove hdkeycache

### PR DESCRIPTION
**Pull request by gabegattis**
#96

### CODE REVIEW

**Comment by matiu** [comment]
thanks is the motivation for this?  Key derivation is VERY slow in JS.

**Comment by braydonf** [comment]
Regarding the speed of derivation, FWIW: https://github.com/cryptocoinjs/hdkey implements derivivaiton using secp256k1 C bindings which is much faster, and bcoin has also started to do something similar at https://github.com/bcoin-org/bcoin/tree/master/lib/hd though is still using cache.

**Comment by matiu** [comment]
Right. That would be great but we also need key derivation in pure JS for
the browser (for copay for example)

**Comment by fanatid** [comment]
@matiu secp256k1 uses elliptic in browser

**Comment by gabegattis** [comment]
@matiu How often are we actually re-deriving a key that we previously derived? It seems like that would be a very rare situation. We don't reuse addresses in Copay, so it seems like we would normally just derive a key once and never need it again.

**Comment by kleetus** [comment]
@gabegattis based on conversations, both in this thread and external, is this code still ready to merge?

**Comment by isocolsky** [comment]
ACK

**Comment by kleetus** [comment]
ACK

**Pull request merged**
