### PR TITLE
avoid using Array.apply(new Array(), buf) for compatability

### PR DESCRIPTION
**Pull request by rubensayshi**
was running some unit tests using `phantomjs`, got funky err:
```
TypeError: '*l' is not a valid argument for 'Function.prototype.apply' (evaluating 'new Array()')
```

this seemed like a logical fix

### CODE REVIEW

**Comment by braydonf** [comment]
Any idea if there is a performance difference?

**Comment by rubensayshi** [comment]
probably, but the old one doesn't work in `phantomjs` and I suspect also not on some older browsers.

the `bufferUtil.reverse` function was already there, and I know `bitcoinjs-lib` uses https://github.com/crypto-browserify/buffer-reverse, which does exactly the same as `bufferUtil.reverse`

**Comment by braydonf** [comment]
Just did a comparison and there isn't much of a difference between before and after, and may be a slight bit faster.

**Comment by braydonf** [comment]
LGTM

**Pull request merged**
