### PR TITLE
fix Script.set

### PR DESCRIPTION
**Pull request by fanatid**
Original PR: https://github.com/bitpay/bitcore/pull/1346

### CODE REVIEW

**Comment by eordano** [comment]
Just bumped into this issue. Can we merge it?

CC: @braydonf

**Comment by braydonf** [comment]
The original PR mentioned `tx.outputs[1].script` as being `null`. 

```js
var script = bitcore.Script(tx.outputs[1].script)
```

However `tx.outputs[1].script` should already be an instance of Script if it's able to be parsed, otherwise it will return `null`, and using the raw buffer is necessary `._scriptBuffer`, and in that case `var script = bitcore.Script(tx.outputs[1]._scriptBuffer)` will throw an error.

**Comment by matiu** [comment]
ACK

**Comment by fanatid** [comment]
1 day before 2 year old 🎉

**Pull request merged**
