### PR TITLE
Script: Account for reverseMap name inconsistencies

### PR DESCRIPTION
**Pull request by braydonf**
There are a few cases where the opcode name doesn't match the name exactly.
These are mostly related with data pushes, and the cases for `OP_0` and `OP_1NEGATE` were
not handled as data pushes as the buf.length was 0. This adds these exceptions to the
`_chunkToString` method on Script.

References:
- https://github.com/bitcoin/bitcoin/blob/e54ebbf6009716a7abcd4d8d3f7bd910e88decdc/src/script/script.cpp#L13
- https://github.com/bitcoin/bitcoin/blob/e54ebbf6009716a7abcd4d8d3f7bd910e88decdc/src/core_write.cpp#L75

Closes: https://github.com/bitpay/insight-api/issues/423

### CODE REVIEW

**Comment by foowie** [comment]
Hello,

can you merge this fix please? I want to switch to new insight-api, but I can't use it because of this issue.

Thank you
Daniel

**Comment by foowie** [comment]
Any news about merging this fix?

**Comment by braydonf** [comment]
I'll take another pass at this, to verify, and see if we can move this forward.

**Comment by braydonf** [comment]
FYI, this shouldn't affect insight-api or bitcore-node, as the ASM is from bitcoind directly now.

**Comment by matiu** [comment]
ACK

**Pull request merged**
