### PR TITLE
replace OP_NOP2 with OP_CHECKLOCKTIMEVERIFY , add OP_CHECKSEQUENCEVERIFY

### PR DESCRIPTION
**Pull request by Cofresi**
Currently, if someone wants to build a script adding OP_CHECKLOCKTIMEVERIFY with
bitcore.Script.add('OP_CHECKLOCKTIMEVERIFY');
OP_NOP2 is added to the script, because it is still inside opcode.js having the index 177 as OP_CHECKLOCKTIMEVERIFY.
I don't see how this could be intended behaviour. Additionally this adds 
OP_CHECKSEQUENCEVERIFY to the list of opcodes.
This pull request would bring opcode.js to the current state of bitcoin core 
https://github.com/bitcoin/bitcoin/blob/master/src/script/script.cpp#L132-L133

### CODE REVIEW

**Comment by matiu** [comment]
Concept ACK. Please fix tests.

**Comment by glen-testing** [comment]
I don't see OP_CHECKSEQUENCEVERFIY in the list of OP codes here: https://github.com/bitpay/bitcore-lib/blob/master/lib/opcode.js
Is there anything I can do to help get OP_CHECKSEQUENCEVERIFY included? 

If not, am I able to manually input 178 into script transactions as a workaround?

**Comment by matiu** [comment]
Hi, this is already implemented and merged on the bitcoin-cash branch and we will be backporting it to master this week: https://github.com/bitpay/bitcore-lib/pull/225

**Comment by matiu** [comment]
https://github.com/bitpay/bitcore-lib/pull/235

**Pull request closed without merging**
