### PR TITLE
create-hash instead crypto.createHash

### PR DESCRIPTION
**Pull request by fanatid**
Related issue: #43 

|  | bitcore-lib.js | bitcore-lib.min.js |
| :-: | :-: | :-: |
| old | 1523428 | 610621 |
| new | 1193748 | 420662 |
| change | -22% | -31% |

[create-hash](https://github.com/crypto-browserify/createHash) and [randombytes](https://github.com/crypto-browserify/randombytes) will be used in any case by `browserify` through [crypto-browserify](https://github.com/crypto-browserify/crypto-browserify)

### CODE REVIEW

**Comment by braydonf** [comment]
Interesting, it looks like the savings comes from not browserifying all of the crypto library? Since both browser and node are implemented in `lib/crypto/random.js` presumably we wouldn't need randombytes as well.

**Comment by fanatid** [comment]
oh, I see, but you need `randombytes`, because if you can't use `require('crypto')`

**Comment by fanatid** [comment]
You can drop `getRandomBufferNode` and `getRandomBufferBrowser` on major release.

**Comment by braydonf** [comment]
It may be possible to have browserify not include crypto, by excluding it with the browserify command.

**Comment by fanatid** [comment]
Indeed. But using `randombytes` is easier, is not it?
What's you prefer? `randombytes` or `crypto` (with additional field for browserify in package.json)

**Comment by matiu** [comment]
Sorry the delay if merging this.

What would happen if window.crypto is not available? It is import to fail in that case (vs generating non crypto random).

**Comment by matiu** [comment]
Closing, too old / stalled. Please reopen if active.

**Pull request closed without merging**
